[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding="82SHxVjmSnA3jwhPAmbB517HPyxLanDQWeAtnSHZWGhD"
# crowdfunding = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
[registry]
url = "https://api.apr.dev"

# [provider]
# cluster = "localnet"
# wallet = "/root/.config/solana/id.json"
[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
